version: "3.9"

services:
  app:
    image: php:8.3-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: bash -c "apt-get update && apt-get install -y \
      git unzip zip libpng-dev libonig-dev libxml2-dev \
      && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd intl \
      && php-fpm"

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
